version: "3"
services: 
  api: 
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8000:8000"
    environment: 
      MONGODB_URI: mongodb://root:admin@db:27017
    depends_on: 
      - db
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: